# on:
#   pull_request:
#     branches:
#       - main
#       - master
#   push:
#     branches:
#       - main
#       - master
#       - develop
# name: "Build & Release"
# jobs:
#   build:
#     name: Build & Release
#     runs-on: windows-latest
#     # runs-on: macos-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-java@v3
#         with:
#           distribution: 'zulu'
#           java-version: '17'
#       - uses: subosito/flutter-action@v2
#         with:
#           channel: 'stable'
#           architecture: x64

#       - run: flutter build apk --release 
#       # - run: flutter build apk --release --split-per-abi
#       # - run: |
#       #     flutter build ios --no-codesign
#       #     cd build/ios/iphoneos
#       #     mkdir Payload
#       #     cd Payload
#       #     ln -s ../Runner.app
#       #     cd ..
#       #     zip -r app.ipa Payload
#       - name: Push to Releases
#         uses: ncipollo/release-action@v1
#         with:
#           artifacts: "build/app/outputs/apk/release/*,build/ios/iphoneos/app.ipa"
#           tag: v1.0.${{ github.run_number }}
#           token: ${{ secrets.TOKEN }}






# # push to master, main, develop
# # pull request on main master



on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: "Build & Release"

jobs:
  build:
    name: Build & Release
    runs-on: windows-latest
    # Only create releases on push to main/master, not on PRs or develop
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Build Android APK
        run: flutter build apk --release 
        
      # Uncomment these lines if you want to build iOS as well
      # - name: Build iOS IPA
      #   run: |
      #     flutter build ios --no-codesign
      #     cd build/ios/iphoneos
      #     mkdir Payload
      #     cd Payload
      #     ln -s ../Runner.app
      #     cd ..
      #     zip -r app.ipa Payload

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          # Use the built-in GITHUB_TOKEN instead of custom TOKEN
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          generateReleaseNotes: true
          makeLatest: true
          # Remove iOS artifacts since you're not building iOS currently
          # artifacts: "build/app/outputs/apk/release/*,build/ios/iphoneos/app.ipa"